title: Hadad Karsa # your name (or website title) here
logo: "/images/hadadkarsa.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor of Computer Science (S.Kom) || Bangkit Academy 2023 Graduate || TensorFlow Developer Certified (TFD Certified)
  <br><br>
  I am a fresh graduate with competent skills in data and information technology. Always growing and adapting.
  <br><br>
  <a href="https://www.linkedin.com/in/hadadkarsa/">View My LinkedIn Profile</a> 
  

plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
